### ISSUE TITLE
v0.4 Release Tracking Issue

### ISSUE THREAD

**Issue by CosmicHorrorDev** [trimental/inlyne#196]
_Content will be updated in the future. Consider this a living document_

---

At the _bare minimum_ these are blockers that need to be addressed before the release

## Blockers

- [x] ~~We  currently have several git dependencies that we need to update to their new releases so that we can publish to [crates.io](https://crates.io)~~
  - [x] ~~`taffy`~~ #210 
  - [x] ~~`glyphon`~~ #214 
- [x] #197
- [x] #141
- [x] #135
  - Could be disabled before release if needed (spoilers: it was vv)
  - #244
- [x] ~~#229~~
  - Niche enough of a situation that it's not worth blocking release
- [x] Currently unreleased, but we have new features for x11 and wayland that disable the clipboard with wayland. We should fix things so that the clipboard works on both. Evaluate what other similar crates do in the ecosystem
  - #243 Adds clipboard support for wayland and fleshes out the featuers

**Comment by Valentin271** [comment]
Should `taffy` and `glyphon` switch to using crates.io version instead of github ones?

**Comment by CosmicHorrorDev** [comment]
Yup! That's the first bullet point under _Blockers_

**Comment by Valentin271** [comment]
I can work on updating that.

**Comment by CosmicHorrorDev** [comment]
Worth noting that #135 isn't a blocker for a release since it's a new feature that we can just disable before releasing

**Comment by CosmicHorrorDev** [comment]
Alright, I'm kicking the last couple of blockers (footnotes are now temporarily disabled, and re-sizing perf isn't worth blocking release imo), so it's time to start riding the release train :steam_locomotive::dash::dash:

**Comment by CosmicHorrorDev** [comment]
- [ ] Check for unused dependencies
  - `$ cargo +nightly udeps`
- [ ] Bump `version` in `Cargo.toml`
- [ ] Propagate the change to `Cargo.lock`
  - `$ cargo check -p inlyne`
- [ ] Optional: If making a breaking release update the `example.png` link in
  the README to point to the appropriate release branch
- [ ] Update static assets
  - `$ cargo xtask gen`
- [ ] Update `rust-version` in `Cargo.toml`
  - `$ cargo msrv --min 1.60 -- cargo check`
- [ ] Merge changes through a PR or directly to make sure CI passes
- [ ] Publish on crates.io
  - `$ cargo publish`
- [ ] Publish on GitHub by pushing a version tag
  - `$ git tag v{VERSION}` (make sure the branch you are on is up to date)
  - `$ git push upstream/origin v{VERSION}`
- [ ] Make a release announcement on GitHub after the release workflow finishes

**Comment by CosmicHorrorDev** [comment]
The release notes are up to date, so this issue is finally fini :partying_face: 

I'll make a more public announcement tomorrow to try and drum up some more activity
